{
  "formatVersion": "1.1",
  "component": {
    "group": "br.dev.rplus",
    "module": "cup-core",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cup-core-0.2.3.jar",
          "url": "cup-core-0.2.3.jar",
          "size": 34380,
          "sha512": "c618099e2b5957697425c045582756548efe8f77dc00b0b85de15987dbdee3a036b92b1ea6511dd6c47c5961e850aa33c56d2d1732d36f5ef3ef710c6b8dfbc0",
          "sha256": "b4a83b3daa4e3b32288175682a60e7ad727c067e728ed2e57e19a2d84ae1c3fd",
          "sha1": "9eab8c43477df7dbf88bae27eeaf6556d6e84c00",
          "md5": "2de87214044ea217819a9ae901cd5888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.github.f4b6a3",
          "module": "uuid-creator",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "com.github.f4b6a3",
          "module": "ulid-creator",
          "version": {
            "requires": "5.2.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        }
      ],
      "files": [
        {
          "name": "cup-core-0.2.3.jar",
          "url": "cup-core-0.2.3.jar",
          "size": 34380,
          "sha512": "c618099e2b5957697425c045582756548efe8f77dc00b0b85de15987dbdee3a036b92b1ea6511dd6c47c5961e850aa33c56d2d1732d36f5ef3ef710c6b8dfbc0",
          "sha256": "b4a83b3daa4e3b32288175682a60e7ad727c067e728ed2e57e19a2d84ae1c3fd",
          "sha1": "9eab8c43477df7dbf88bae27eeaf6556d6e84c00",
          "md5": "2de87214044ea217819a9ae901cd5888"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cup-core-0.2.3-javadoc.jar",
          "url": "cup-core-0.2.3-javadoc.jar",
          "size": 186687,
          "sha512": "cc4fd738ff888e7723d1839fe26cfc6eed4d327aebae85a82486aa5c9a4d2efe582344681cbb7f5dd176211099502db6015e00e9e84bea65844edd0e57acdac4",
          "sha256": "ce6ac9fc0bda9948c6db05ab3a9796345b705db83dc25807755f0f1863b978a1",
          "sha1": "77300605f091c0d9945b4916c361227bf69c36a0",
          "md5": "b8045bce0d16461429b1e9fcc58c04b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cup-core-0.2.3-sources.jar",
          "url": "cup-core-0.2.3-sources.jar",
          "size": 22554,
          "sha512": "1c2644dda8378925e153a019877a82a9c7278f98b074a1a3cc3be1b222ffd6d71fd7acd1500667519986b5dc5abc59a59f2707cf6a83a15981de7f905b8dcf51",
          "sha256": "91365a89fa4db5226bdbe86cd21fbb7a11824430188b0c5ec90cae91811dae0f",
          "sha1": "5502b2acb24ea136d93f1c0275647fa661a6ff36",
          "md5": "1838028219aa287c22c32601b8bf5428"
        }
      ]
    }
  ]
}
