name: Publish Javadoc to GitHub Pages

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project and generate Javadoc
        run: |
          ./gradlew clean aggregateJavadoc

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m ":memo: Deploy id ${{ github.run_id }}" || true

      - name: Deploy Javadoc to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build/docs/javadoc
          github_token: ${{ secrets.TOKEN }}
          commit_message: ":memo: Deploy id ${{ github.run_id }} | "
