{
  "formatVersion": "1.1",
  "component": {
    "group": "br.dev.rplus",
    "module": "cup-objects",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cup-objects-0.2.3.jar",
          "url": "cup-objects-0.2.3.jar",
          "size": 13647,
          "sha512": "573253062bf42b8114da0585c55ca0c98a2097696479c1d25c3638f791b5d926b8321bb54fa577963e625711997e5854be3448380d170a81aff77b2fdb621937",
          "sha256": "6560a46b77770886972bf79e8787613099d9e33a1cf36587cccda14df00b1080",
          "sha1": "4782747a9898b3f401d782ed5092f0270f3bfcee",
          "md5": "34363d92b07dcf2865f08a82f6d72311"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "br.dev.rplus",
          "module": "cup-core",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.19.1"
          }
        }
      ],
      "files": [
        {
          "name": "cup-objects-0.2.3.jar",
          "url": "cup-objects-0.2.3.jar",
          "size": 13647,
          "sha512": "573253062bf42b8114da0585c55ca0c98a2097696479c1d25c3638f791b5d926b8321bb54fa577963e625711997e5854be3448380d170a81aff77b2fdb621937",
          "sha256": "6560a46b77770886972bf79e8787613099d9e33a1cf36587cccda14df00b1080",
          "sha1": "4782747a9898b3f401d782ed5092f0270f3bfcee",
          "md5": "34363d92b07dcf2865f08a82f6d72311"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cup-objects-0.2.3-javadoc.jar",
          "url": "cup-objects-0.2.3-javadoc.jar",
          "size": 129237,
          "sha512": "86fa8ed6d1a6d1ca9fdfff143e6bae86f00ae549fb8238d094a15ee70f1108393d252eeac87f60566fcdda77001fda7ee006c3611389d2976b5a58929d2b96f0",
          "sha256": "1020779de1146613e9ea443b5ac2fc47f551005685fbe3984ade8d260edd0596",
          "sha1": "084f9e95ac8aa41e4696fda63b91f5ae975369a5",
          "md5": "b1b5bca077bc52de86b54ea5cfb15b05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cup-objects-0.2.3-sources.jar",
          "url": "cup-objects-0.2.3-sources.jar",
          "size": 8525,
          "sha512": "e2885184ef1e3dd7915fa78f4f5be84f82cbf04ea8b571f235248bf944e5a17760f604850d93b4c95ebddcb97e363552abd5128e484e4aa07b346d4c87fd4314",
          "sha256": "3a3837b53b61d527a388d2cf0649d2a8a0a085ebac399eb9ff82e82f3bb7dcdb",
          "sha1": "64ac579269b6d61f4099d77fcb1bb4e544779701",
          "md5": "d9c3d446c5ed88a9baa7d71207b38e2e"
        }
      ]
    }
  ]
}
